version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - thelper
    - unused
