run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - thelper
    - unused
